on:
  workflow_call:
    inputs:
      openstack-release:
        description: OpenStack release
        type: string
        required: true

env:
  SNAP_REPO_PATH: snap-tempest
  AUTOMATION_REPO_PATH: snap-tempest-automation

jobs:
  update-snapcraft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout snap-tempest
        uses: actions/checkout@v4
        with:
          repository: canonical/snap-tempest
          ref: stable/${{ inputs.openstack-release }}
          path: ${{ env.SNAP_REPO_PATH }}
      - name: Checkout snap-tempest-automation
        uses: actions/checkout@v4
        with:
          ref: main
          path: ${{ env.AUTOMATION_REPO_PATH }}
      - name: Install tox
        run: |
          sudo apt-get update
          sudo apt-get install --yes tox
      - name: Update Snapcraft YAML
        id: update_snapcraft
        run: |
          tox -c ${{ env.AUTOMATION_REPO_PATH }}/tox.ini -e release -- \
              --input ${{ env.SNAP_REPO_PATH }}/snap/snapcraft.yaml \
              --output ${{ env.SNAP_REPO_PATH }}/snap/snapcraft.yaml \
              --release ${{ inputs.openstack-release }} \
              --manual-requirements ${{ env.SNAP_REPO_PATH }}/requirements-manual.txt \
              --excluded-plugins ${{ env.SNAP_REPO_PATH }}/excluded-plugins.txt
          cd ${{ env.SNAP_REPO_PATH }} && git diff --exit-code snap/snapcraft.yaml \
              && echo "create_pr=0" >> $GITHUB_OUTPUT \
              || echo "create_pr=1" >> $GITHUB_OUTPUT
      - name: Create Pull Request
        if: ${{ steps.update_snapcraft.outputs.create_pr == 1 }}
        uses: peter-evans/create-pull-request@v6
        id: create_pr
        env:
          GITHUB_TOKEN: ${{ github.token }}  # Use the auto-generated action token
        with:
          token: ${{ github.token }}  # Use the auto-generated action token
          path: ${{ env.SNAP_REPO_PATH }}
          title: "release(${{ inputs.openstack-release }}): update snapcraft.yaml"
          commit-message: |
            release(${{ inputs.openstack-release }}): update snapcraft.yaml

            This commit has been generated by
            canonical/snap-tempest-automation/actions/workflows/update-tempest-releases.yaml
          branch: release/${{ inputs.openstack-release }}
      - name: PR outputs
        if: ${{ steps.create_pr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
